#!/bin/bash -l

/usr/bin/dos2unix -q ${BASH_ARGV[0]}

#$ -P bf528
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

##Loading modules

module load python3
module load rseqc/3.0.0
module load samtools/0.1.19

#Calculate the RNA-seq reads coverage over gene body
geneBody_coverage.py -i accepted_hits.bam -r /project/bf528/project_2/reference/annot/mm9.bed -o rseqcgB

#calculates the inner distance(insert distance) of RNA-seq fragments
inner_distance.py -i accepted_hits.bam -r /project/bf528/project_2/reference/annot/mm9.bed -o rseqcindist

#Summarizing mapping statistics of BAM or SAM files
bam_stat.py -i accepted_hits.bam
